add project structure
ChoosingWaifu/java-explore-with-me pull request #1
Opened 2022-11-15 17:19 UTC by ChoosingWaifu

controllers
dockerfiles
pom files

2022-12-02 20:12 UTC, krylov-sergey-sergeevich requested changes
Привет, работа хорошая - давай сделаем ее лучше:

1) Маловато аннотаций Transaction давай накинем где они уместны и не забудем про readOnly где нужно
2) В многих местах можно получше попытаться подумать и избежать дублирования кода, рекомендую самому посмотреть PR сверху вниз и заметишь сразу же
3) Отлично что логи сделаны на англ языке, это хорошая практика
4) Подход с исключениями хорош, но можно лучше. Исключения если присмотреться похожи по структуре, не хочется ли создать структуру исключений или побольше кастомных исключений и не писать каждый раз весь текст причины исключения, а чисто название например NotFoundCategoryException extend NotFoundException это не обязательно, но как на подумать.
5) Не обязательно сейчас, но для развития на будущее: почитай про Swagger и Mapstruct
6) Как совет: рекомендую не лепить очень длинные имена derived query методов. Если имя метода длинное — использовать аннотацию @Query для описания запроса.
7) Подумать о том какие поля могут быть уникальны и докинуть им ограничения

Буду ждать с доработками, если что доступен в слаке =)

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on README.md
>  https://github.com/ChoosingWaifu/java-explore-with-me/pull/1
ReadMe давай оформим получше: **"Добавим блоки"**

1) Используемые технологии
2) Краткое описание сервисов
3) Команды описаны для старта докера

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/java/explorewithme/category/dto/CategoryMapper.java
> +public class CategoryMapper {
Рекомендую почитать на будущее про Mapstruct, но сейчас тут его применять излишне

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/java/explorewithme/errors/ErrorHandler.java
> +public class ErrorHandler {
Попробуй поизучать как можно сделать так чтобы еще возвращать в сообщение с ошибкой request path по которому был сделан запрос. Один из вариантов это воспользоваться: **HttpServletRequest**

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/java/explorewithme/event/interaction/EventClient.java
> +    @SuppressWarnings("unchecked")
Ну мы понимаем же что это плохая практика и должна быть прям Причина по которой мы так делаем?

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/java/explorewithme/event/repository/EventRepository.java
> +    List<Event> findByCategory_IdIs(Long category);
Почему в названиях _ присутствует тут и ниже?

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/java/explorewithme/pagination/PageFromRequest.java
> +    public PageFromRequest(int offset, int size, Sort sort) {
Хороший класс

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Как будто чутка поехал код по стилю

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
И никаких delete cascad и других интересных вещей, предлагаю еще раз глянуть и возможно найдем что улучшить

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/resources/schema.sql
> +                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Лично мне больше нравится primary key делать руками вот так: 
id    BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,

CONSTRAINT pk_user PRIMARY KEY (id),

Но тут не критично и каждому свое

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on mainService/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Подумать мжт какие вещи могут быть обязательно уникальными и им можно повесить UNIQUE constraint

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on statsService/src/main/java/explorewithme/repository/StatsRepository.java
> +public interface StatsRepository extends JpaRepository<Hit, Long> {
Как будто местами переусложнено, но выглядит правдоподобно

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on statsService/src/main/java/explorewithme/repository/StatsRepository.java
> +public interface StatsRepository extends JpaRepository<Hit, Long> {
И это все же HitRepository

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on statsService/src/main/resources/schema.sql
> +    uri       VARCHAR      NOT NULL,
А тут размер?

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on statsService/src/main/resources/schema.sql
> +    timestamp TIMESTAMP    NOT NULL
timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

2022-12-02 20:12 UTC, krylov-sergey-sergeevich commented on statsService/src/main/resources/schema.sql
> +    timestamp TIMESTAMP    NOT NULL
Это не обязательно, просто так лучше (на будущее)

2022-12-04 09:32 UTC, ChoosingWaifu commented on README.md
>  https://github.com/ChoosingWaifu/java-explore-with-me/pull/1
добавил описание, технологии, раздел про докр, но не до конца понял что конкретно про докер нужно было

2022-12-04 09:33 UTC, ChoosingWaifu commented on mainService/src/main/java/explorewithme/category/dto/CategoryMapper.java
> +public class CategoryMapper {
насчет всего маппинга,  у меня он не очень вышел и дублирование именно там у меня, но я не решился менять, т.к его очень много, и за работоспособность проекта переживал, я думал в feature сделать рефактор мапинга.

2022-12-04 09:35 UTC, ChoosingWaifu commented on mainService/src/main/java/explorewithme/event/interaction/EventClient.java
> +    @SuppressWarnings("unchecked")
я прочитал по этой теме, ноя не до конца понял в каком классе и что менять или какую проверку произвести чтобы не было warning'a, добавил аннотацию чтобы просто его не было, но понимаю что это только дополнительный риск создает, наверное не стоило

2022-12-04 09:36 UTC, ChoosingWaifu commented on mainService/src/main/java/explorewithme/event/repository/EventRepository.java
> +    List<Event> findByCategory_IdIs(Long category);
Сделал по предложению идеи, прочитал про разницу между x_Id и xId и вроде у меня не требуется оно, переделал

2022-12-04 09:37 UTC, ChoosingWaifu commented on mainService/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
исправил, добавил unique и delete cascade где нашел

2022-12-04 09:37 UTC, ChoosingWaifu commented on mainService/src/main/resources/schema.sql
> +                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
переделал под такой вид CONSTRAINT pk_user PRIMARY KEY (id),

2022-12-04 09:37 UTC, ChoosingWaifu commented on statsService/src/main/java/explorewithme/repository/StatsRepository.java
> +public interface StatsRepository extends JpaRepository<Hit, Long> {
переименовал

2022-12-04 09:37 UTC, ChoosingWaifu commented on statsService/src/main/resources/schema.sql
> +    uri       VARCHAR      NOT NULL,
добавил размеры

2022-12-04 09:37 UTC, ChoosingWaifu commented on statsService/src/main/resources/schema.sql
> +    timestamp TIMESTAMP    NOT NULL
добавил  WITHOUT TIME ZONE

2022-12-04 09:38 UTC, ChoosingWaifu commented on mainService/src/main/java/explorewithme/errors/ErrorHandler.java
> +public class ErrorHandler {
не успел

2022-12-04 09:39 UTC, ChoosingWaifu commented on README.md
>  https://github.com/ChoosingWaifu/java-explore-with-me/pull/1
добавил также @transactional и read only, переделал not found исключения во всех классах

2022-12-04 09:42 UTC, ChoosingWaifu commented on mainService/src/main/java/explorewithme/event/interaction/EventClient.java
> +    @SuppressWarnings("unchecked")
пока не понял как проверить class cast

2022-12-04 09:46 UTC, ChoosingWaifu commented on mainService/src/main/java/explorewithme/event/interaction/EventClient.java
> +    @SuppressWarnings("unchecked")
Нужно просто передать другой объект, параметризированный, а не object?

2022-12-04 17:48 UTC, krylov-sergey-sergeevich commented on mainService/src/main/java/explorewithme/errors/ErrorHandler.java
> +public class ErrorHandler {
Вообщем там основной метод нужный getPathRequest вроде так пишется

2022-12-04 17:50 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки

Вот теперь работа выглядит хорошо, видно что вы овладели языком Java. Поэтому зачет и удачи в дальнейшем обучение =)

2022-12-04 20:08 UTC, merged